### ISSUE TITLE
[Request] Manually adjusting display size and placement

### ISSUE THREAD

**Issue by Samswich** [ThatGravyBoat/Craftify#63] opened 2023-07-10 02:47 UTC
The song display takes up a lot of space on the screen, so I think it would be better if you could manually change the display size and placement on the screen depending on preference.

**Comment by ThatGravyBoat** [comment] 2023-07-10 04:54
You can already change the placement and size is a duplicate of #48

**Closed by ThatGravyBoat** 2023-07-10 04:54 UTC
