### ISSUE TITLE
Local files not being showed up correctly

### ISSUE THREAD

**Issue by tajemniktv** [ThatGravyBoat/Craftify#42] opened 2023-04-18 00:13 UTC
As per #37
Full logs: https://mclo.gs/NnvRrAF
Error: https://mclo.gs/1WGEYn2

Example: Having a local file in liked songs causes the local song not to appear in the frame. Then it "breaks" the mod completely (not showing new songs, controlls not working)

**Comment by ThatGravyBoat** [comment] 2023-04-18 01:35
Duplicate of #39

**Closed by ThatGravyBoat** 2023-04-18 01:35 UTC
