### ISSUE TITLE
Cider 2 problems

### ISSUE THREAD

**Issue by sebx140** [ThatGravyBoat/Craftify#139] opened 2024-12-24 19:50 UTC
With the new Cider 2.5.0 they added some api keys so external apps can connect through, can this be added so i can connect again?
Oh and we need support for the Ver 1.21.4

**Comment by ThatGravyBoat** [comment] 2024-12-24 20:25
Duplicate of #136 and #137

**Closed by ThatGravyBoat** 2024-12-24 20:25 UTC
