### ISSUE TITLE
Size Settings

### ISSUE THREAD

**Issue by ntExistTW** [ThatGravyBoat/Craftify#76] opened 2023-09-17 10:47 UTC
Adding font size and interface.
With a generally small interface, text becomes almost invisible over time.
![UI Scale x2](https://i.imgur.com/RCb03it.png)

**Comment by Neop0litan** [comment] 2023-09-20 00:44
This would be really nice, currently the only way we can scale the overlay is by changing the GUI scale of Minecraft itself which can mess up other mods and just generally go against how people like their Minecraft configured.

**Comment by ThatGravyBoat** [comment] 2023-11-09 07:31
Duplicate of #48

**Closed by ThatGravyBoat** 2023-11-09 07:31 UTC
